In [40]:
import numpy as np

In [41]:
a = np.array([[1, 2, 3, 99],
              [4, 5, 6, 999],
              [7, 8, 9, 9999],
              (10, 11, 12, 99999)])

i = 0
while i < 3:
    j = 1
    while j < 4:
        a[i][j], a[j][i] = a[j][i], a[i][j]
        j = j + 1
    i = i + 1

In [42]:
print(a)

[[    1     4     7    10]
 [    2     5     6    11]
 [    3     8     9    12]
 [   99   999  9999 99999]]
