In [1]:
import numpy as np

In [6]:
a = np.arange(0, 18)
print(a)

b = np.arange(20, 38)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]


In [14]:
a = a.reshape(6, 3)
print("Array a: ", end="")
print(a)

b = b.reshape(6, 3)
print("Array b: ", end="")
print(b)

Array a: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
Array b: [[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]


In [8]:
print(a + b)

[[20 22 24]
 [26 28 30]
 [32 34 36]
 [38 40 42]
 [44 46 48]
 [50 52 54]]
